### ISSUE TITLE
About the data

### ISSUE THREAD

**Issue by ghost** [comp-journalism/2016-03-wapo-uber#1]
I was wondering why there are two records for most locations within one time stamp? And it seems that one of these two records in the same location usually has 1.0 surge price factor.  
But it seems that in the code we can only find one request at each location in each time slot.

Thanks a lot!

**Comment by JAStark** [comment]
Yes - that is because the Uber API we were using required a start location and an ending location. Because we were only interested in the surge price and wait time for the start location, we entered the same longitude and latitude for both the start and end location.

**Comment by ghost** [comment]
I mean, why two requests in the same time with same start location and ending location have different responses of wait time and surge price, e.g., following records:
2016-02-03 22:18:26,1.5,180,uberX,7,8,40,40
2016-02-03 22:18:26,1.0,240,uberX,5,6,40,40
Thanks a lot!

**Comment by JAStark** [comment]
<img width="783" alt="screen shot 2016-11-03 at 17 21 05" src="https://cloud.githubusercontent.com/assets/7544235/19985650/0049d756-a1ea-11e6-9518-2358a46629b7.png">

Here is a screenshot of the .csv.  We have just one row for each location at each time point. There is only one Surge Price per row, so only one per time point per location. 

It looks like your examples are of _different_ locations: Location_id 180 and Location_id 240.

**Comment by ghost** [comment]
sorry I don't know if I understand,  but from the data file you provide on google drive, ''TractsSurgeDC2_Feb4_Mar2.csv'', the fifth line is:
![image](https://cloud.githubusercontent.com/assets/23182836/19988739/1f2442c0-a1df-11e6-8450-258e537222cf.png)
and the 726th line:
![image](https://cloud.githubusercontent.com/assets/23182836/19988760/440a2046-a1df-11e6-9ef1-8e9ea161306b.png)
which both shows uberX data at 2016-02-03 22:18:26, both from and to location ID 40, but with different surge price factor and wait time, and basically most records appear twice with different wait time and surge price within the same time and same starting and ending location ID.

**Comment by JAStark** [comment]
Sorry for the delay. I just want you to know that we are looking into it, and will let you know when we've figured it out! Thanks for posting this!

**Comment by JAStark** [comment]
Thank you @romelf . The bug has now been fixed. Please refer to the "Corrected" branch for new code and links to new data.
